spring:

# 원격 연결시 적용
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/baedeokcar
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      # application 실행시 모든 테이블 drop 후, create
      # 개발 단계에서만 적용
      ddl-auto: create

    properties:
      hibernate:
        # 콘솔에 sql을 보여준다. 성능 점검 필요
#        show_sql: true
        # sql 포맷에 맞춰서 보여준다.
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb

logging.level:
  org.hibernate.SQL: debug