spring:

  # 원격 연결시 적용
  #  datasource:
  #    url: jdbc:h2:tcp://localhost/~/baedeokcar
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      # 변경이 필요하면 alter, 테이블이 없는 경우 create
      ddl-auto: update

    # application 실행시 모든 테이블 drop 후, create
    # 개발 단계에서만 적용
    #ddl-auto: create


    properties:
      hibernate:
        # 콘솔에 sql을 보여준다. 성능 점검 필요
        # show_sql: true
        # sql 포맷에 맞춰서 보여준다.
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    # url: jdbc:h2:mem:testdb
    url: jdbc:h2:tcp://localhost/~/baedeokcar
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # 프로젝트 변경 후에 만들어진 결과를 보관(캐싱)하지 않도록 설정
  thymeleaf:
    cache: false

logging.level:
  org.hibernate.SQL: debug
